// Package frontend embeds the production web interface for the desktop app.
package frontend

import "embed"

// Assets contains the interface generated by npm run build.
//
//go:embed all:dist
var Assets embed.FS
